//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.srGuardaDatosCorrectivos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srGuardaDatosCorrectivos.wsGuardaDatosCorrectivosSoap")]
    public interface wsGuardaDatosCorrectivosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregaDatosCorrectivos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void agregaDatosCorrectivos(CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva medida_Correctiva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregaDatosCorrectivos", ReplyAction="*")]
        System.Threading.Tasks.Task agregaDatosCorrectivosAsync(CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva medida_Correctiva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/entregaMedida_CorrectivaDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet entregaMedida_CorrectivaDataSet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/entregaMedida_CorrectivaDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> entregaMedida_CorrectivaDataSetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/entregaLargoMedida_Correctiva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva[] entregaLargoMedida_Correctiva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/entregaLargoMedida_Correctiva", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva[]> entregaLargoMedida_CorrectivaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/entregaPosicionMedida_Correctiva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva entregaPosicionMedida_Correctiva(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/entregaPosicionMedida_Correctiva", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva> entregaPosicionMedida_CorrectivaAsync(int pos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarMedida_Correctiva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva buscarMedida_Correctiva(string Cod_MC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarMedida_Correctiva", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva> buscarMedida_CorrectivaAsync(string Cod_MC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMedidaCorrectiva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarMedidaCorrectiva(string Cod_MC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMedidaCorrectiva", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarMedidaCorrectivaAsync(string Cod_MC);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medida_Correctiva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cod_MCField;
        
        private string cod_Detalle_FichaField;
        
        private string cod_TMCField;
        
        private string descripcionField;
        
        private System.DateTime fecha_InicioField;
        
        private System.DateTime fecha_TerminoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cod_MC {
            get {
                return this.cod_MCField;
            }
            set {
                this.cod_MCField = value;
                this.RaisePropertyChanged("Cod_MC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cod_Detalle_Ficha {
            get {
                return this.cod_Detalle_FichaField;
            }
            set {
                this.cod_Detalle_FichaField = value;
                this.RaisePropertyChanged("Cod_Detalle_Ficha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cod_TMC {
            get {
                return this.cod_TMCField;
            }
            set {
                this.cod_TMCField = value;
                this.RaisePropertyChanged("Cod_TMC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Fecha_Inicio {
            get {
                return this.fecha_InicioField;
            }
            set {
                this.fecha_InicioField = value;
                this.RaisePropertyChanged("Fecha_Inicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime Fecha_Termino {
            get {
                return this.fecha_TerminoField;
            }
            set {
                this.fecha_TerminoField = value;
                this.RaisePropertyChanged("Fecha_Termino");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsGuardaDatosCorrectivosSoapChannel : CapaGUI.srGuardaDatosCorrectivos.wsGuardaDatosCorrectivosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsGuardaDatosCorrectivosSoapClient : System.ServiceModel.ClientBase<CapaGUI.srGuardaDatosCorrectivos.wsGuardaDatosCorrectivosSoap>, CapaGUI.srGuardaDatosCorrectivos.wsGuardaDatosCorrectivosSoap {
        
        public wsGuardaDatosCorrectivosSoapClient() {
        }
        
        public wsGuardaDatosCorrectivosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsGuardaDatosCorrectivosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGuardaDatosCorrectivosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGuardaDatosCorrectivosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void agregaDatosCorrectivos(CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva medida_Correctiva) {
            base.Channel.agregaDatosCorrectivos(medida_Correctiva);
        }
        
        public System.Threading.Tasks.Task agregaDatosCorrectivosAsync(CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva medida_Correctiva) {
            return base.Channel.agregaDatosCorrectivosAsync(medida_Correctiva);
        }
        
        public System.Data.DataSet entregaMedida_CorrectivaDataSet() {
            return base.Channel.entregaMedida_CorrectivaDataSet();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> entregaMedida_CorrectivaDataSetAsync() {
            return base.Channel.entregaMedida_CorrectivaDataSetAsync();
        }
        
        public CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva[] entregaLargoMedida_Correctiva() {
            return base.Channel.entregaLargoMedida_Correctiva();
        }
        
        public System.Threading.Tasks.Task<CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva[]> entregaLargoMedida_CorrectivaAsync() {
            return base.Channel.entregaLargoMedida_CorrectivaAsync();
        }
        
        public CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva entregaPosicionMedida_Correctiva(int pos) {
            return base.Channel.entregaPosicionMedida_Correctiva(pos);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva> entregaPosicionMedida_CorrectivaAsync(int pos) {
            return base.Channel.entregaPosicionMedida_CorrectivaAsync(pos);
        }
        
        public CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva buscarMedida_Correctiva(string Cod_MC) {
            return base.Channel.buscarMedida_Correctiva(Cod_MC);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.srGuardaDatosCorrectivos.Medida_Correctiva> buscarMedida_CorrectivaAsync(string Cod_MC) {
            return base.Channel.buscarMedida_CorrectivaAsync(Cod_MC);
        }
        
        public void eliminarMedidaCorrectiva(string Cod_MC) {
            base.Channel.eliminarMedidaCorrectiva(Cod_MC);
        }
        
        public System.Threading.Tasks.Task eliminarMedidaCorrectivaAsync(string Cod_MC) {
            return base.Channel.eliminarMedidaCorrectivaAsync(Cod_MC);
        }
    }
}
