//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.srEntregaResultadosAlumno {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srEntregaResultadosAlumno.wsGeneraResultadosSoap")]
    public interface wsGeneraResultadosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generaResultados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet generaResultados(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generaResultados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> generaResultadosAsync(string rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsGeneraResultadosSoapChannel : CapaGUI.srEntregaResultadosAlumno.wsGeneraResultadosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsGeneraResultadosSoapClient : System.ServiceModel.ClientBase<CapaGUI.srEntregaResultadosAlumno.wsGeneraResultadosSoap>, CapaGUI.srEntregaResultadosAlumno.wsGeneraResultadosSoap {
        
        public wsGeneraResultadosSoapClient() {
        }
        
        public wsGeneraResultadosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsGeneraResultadosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGeneraResultadosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGeneraResultadosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet generaResultados(string rut) {
            return base.Channel.generaResultados(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> generaResultadosAsync(string rut) {
            return base.Channel.generaResultadosAsync(rut);
        }
    }
}
