//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.srEntregaResultados {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srEntregaResultados.wsEntregaResultadosHistoricosSoap")]
    public interface wsEntregaResultadosHistoricosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntregarResultadosHistoricos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EntregarResultadosHistoricos(string año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EntregarResultadosHistoricos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> EntregarResultadosHistoricosAsync(string año);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsEntregaResultadosHistoricosSoapChannel : CapaGUI.srEntregaResultados.wsEntregaResultadosHistoricosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsEntregaResultadosHistoricosSoapClient : System.ServiceModel.ClientBase<CapaGUI.srEntregaResultados.wsEntregaResultadosHistoricosSoap>, CapaGUI.srEntregaResultados.wsEntregaResultadosHistoricosSoap {
        
        public wsEntregaResultadosHistoricosSoapClient() {
        }
        
        public wsEntregaResultadosHistoricosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsEntregaResultadosHistoricosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEntregaResultadosHistoricosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEntregaResultadosHistoricosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet EntregarResultadosHistoricos(string año) {
            return base.Channel.EntregarResultadosHistoricos(año);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EntregarResultadosHistoricosAsync(string año) {
            return base.Channel.EntregarResultadosHistoricosAsync(año);
        }
    }
}
