//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.srComparaIMC {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srComparaIMC.wsComparaIMCSoap")]
    public interface wsComparaIMCSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comparaIMC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet comparaIMC(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comparaIMC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> comparaIMCAsync(string rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsComparaIMCSoapChannel : CapaGUI.srComparaIMC.wsComparaIMCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsComparaIMCSoapClient : System.ServiceModel.ClientBase<CapaGUI.srComparaIMC.wsComparaIMCSoap>, CapaGUI.srComparaIMC.wsComparaIMCSoap {
        
        public wsComparaIMCSoapClient() {
        }
        
        public wsComparaIMCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsComparaIMCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsComparaIMCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsComparaIMCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet comparaIMC(string rut) {
            return base.Channel.comparaIMC(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> comparaIMCAsync(string rut) {
            return base.Channel.comparaIMCAsync(rut);
        }
    }
}
